steps:
  # Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'artifacts', 'repositories', 'create', 'spurly-middleware',
      '--repository-format=docker',
      '--location=us-west2',
      '--description="Spurly Middleware repository"',
      '--project=$PROJECT_ID'
    ]
    id: 'create-repo'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    waitFor:
      - 'create-repo'
    args: [
      'build',
      '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/spurly-middleware/spurly-middleware:$COMMIT_SHA',
      '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/spurly-middleware/spurly-middleware:latest',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'us-west2-docker.pkg.dev/$PROJECT_ID/spurly-middleware/spurly-middleware:$COMMIT_SHA'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'us-west2-docker.pkg.dev/$PROJECT_ID/spurly-middleware/spurly-middleware:latest'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'spurly-middleware',
      '--image', 'us-west2-docker.pkg.dev/$PROJECT_ID/spurly-middleware/spurly-middleware:$COMMIT_SHA',
      '--region', 'us-west2',
      '--platform', 'managed',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '2',
      '--min-instances', '0',
      '--max-instances', '20',
      '--timeout', '900',
      '--concurrency', '100',
    ]
    id: 'deploy-cloud-run'
    waitFor:
      - 'push'

# Service account configuration
serviceAccount: 'projects/boreal-sweep-455716-a5/serviceAccounts/firebase-adminsdk-fbsvc@boreal-sweep-455716-a5.iam.gserviceaccount.com'

# Build options
options:
  logging: 'CLOUD_LOGGING_ONLY'
  substitutionOption: 'ALLOW_LOOSE'
  diskSizeGb: '100'

# Timeout for the entire build
timeout: '1800s'

# Optional substitutions (safe to leave)
substitutions:
  _SERVICE_NAME: 'spurly-middleware'
  _REGION: 'us-west2'
