options:
  logging: NONE
logsBucket: "gs://spurly-cloudbuild-logs"
serviceAccount: 'spurly-owner-editor@boreal-sweep-455716-a5.iam.gserviceaccount.com'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/boreal-sweep-455716-a5/spurly-middleware', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/boreal-sweep-455716-a5/spurly-middleware']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'spurly-middleware', '--image', 'gcr.io/boreal-sweep-455716-a5/spurly-middleware', '--region', 'us-west2','--platform', 'managed', '--allow-unauthenticated']
